<?php

/**
 * @file
 * Contains migrate_dmc_floss.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function migrate_dmc_floss_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the migrate_dmc_floss module.
    case 'help.page.migrate_dmc_floss':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Migrate Module for Drupal 7 to 8 of the DMC Floss content type') . '</p>';
      return $output;

    default:
  }
}
